CREATE TABLESPACE STAR_ARCHIVE_DATA 
DATAFILE '+PSTAR_DG_DB001/pstar/datafile/STAR_ARCHIVE_DATA_01.DBF' 
SIZE 1G AUTOEXTEND ON NEXT 128M MAXSIZE UNLIMITED
LOGGING
ONLINE
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;